
#import <Cocoa/Cocoa.h>
#import <BWToolkitFramework/BWToolkitFramework.h>
#import <FullColorWell.h>
#import <PixelImageView.h>
#import "ROM Parser/RomFileReader.h"

@interface AppDelegate : NSObject{
	IBOutlet NSMenu *menu;
	IBOutlet NSWindow *window;
	IBOutlet PixelImageView *mainImageView;
	IBOutlet NSTextField *offsetField;
	IBOutlet NSPopUpButton *modeComboBox;
	IBOutlet NSPopUpButton *layoutComboBox;

	IBOutlet NSPanel *spriteControlsPanel;
	IBOutlet NSPanel *palettePanel;

	IBOutlet NSButton *addOneByte;
	IBOutlet NSButton *addOnePage;
	IBOutlet NSButton *removeOneByte;
	IBOutlet NSButton *removeOnePage;

	IBOutlet BWTransparentSlider *spriteWidthSlider;
	IBOutlet BWTransparentSlider *spriteHeightSlider;
	IBOutlet BWTransparentSlider *spriteRowsSlider;
	IBOutlet BWTransparentSlider *spriteColumnsSlider;
	
	IBOutlet FullColorWell *paletteColor1;
	IBOutlet FullColorWell *paletteColor2;
	IBOutlet FullColorWell *paletteColor3;
	IBOutlet FullColorWell *paletteColor4;
	IBOutlet FullColorWell *paletteColor5;
	IBOutlet FullColorWell *paletteColor6;
	IBOutlet FullColorWell *paletteColor7;
	IBOutlet FullColorWell *paletteColor8;
	IBOutlet FullColorWell *paletteColor9;
	IBOutlet FullColorWell *paletteColor10;
	IBOutlet FullColorWell *paletteColor11;
	IBOutlet FullColorWell *paletteColor12;
	IBOutlet FullColorWell *paletteColor13;
	IBOutlet FullColorWell *paletteColor14;
	IBOutlet FullColorWell *paletteColor15;
	IBOutlet FullColorWell *paletteColor16;
	IBOutlet FullColorWell *paletteColor17;
	IBOutlet FullColorWell *paletteColor18;
	IBOutlet FullColorWell *paletteColor19;
	IBOutlet FullColorWell *paletteColor20;
	IBOutlet FullColorWell *paletteColor21;
	IBOutlet FullColorWell *paletteColor22;
	IBOutlet FullColorWell *paletteColor23;
	IBOutlet FullColorWell *paletteColor24;
	IBOutlet FullColorWell *paletteColor25;
	IBOutlet FullColorWell *paletteColor26;
	IBOutlet FullColorWell *paletteColor27;
	IBOutlet FullColorWell *paletteColor28;
	IBOutlet FullColorWell *paletteColor29;
	IBOutlet FullColorWell *paletteColor30;
	IBOutlet FullColorWell *paletteColor31;
	IBOutlet FullColorWell *paletteColor32;
	IBOutlet FullColorWell *paletteColor33;
	IBOutlet FullColorWell *paletteColor34;
	IBOutlet FullColorWell *paletteColor35;
	IBOutlet FullColorWell *paletteColor36;
	IBOutlet FullColorWell *paletteColor37;
	IBOutlet FullColorWell *paletteColor38;
	IBOutlet FullColorWell *paletteColor39;
	IBOutlet FullColorWell *paletteColor40;
	IBOutlet FullColorWell *paletteColor41;
	IBOutlet FullColorWell *paletteColor42;
	IBOutlet FullColorWell *paletteColor43;
	IBOutlet FullColorWell *paletteColor44;
	IBOutlet FullColorWell *paletteColor45;
	IBOutlet FullColorWell *paletteColor46;
	IBOutlet FullColorWell *paletteColor47;
	IBOutlet FullColorWell *paletteColor48;
	IBOutlet FullColorWell *paletteColor49;
	IBOutlet FullColorWell *paletteColor50;
	IBOutlet FullColorWell *paletteColor51;
	IBOutlet FullColorWell *paletteColor52;
	IBOutlet FullColorWell *paletteColor53;
	IBOutlet FullColorWell *paletteColor54;
	IBOutlet FullColorWell *paletteColor55;
	IBOutlet FullColorWell *paletteColor56;
	IBOutlet FullColorWell *paletteColor57;
	IBOutlet FullColorWell *paletteColor58;
	IBOutlet FullColorWell *paletteColor59;
	IBOutlet FullColorWell *paletteColor60;
	IBOutlet FullColorWell *paletteColor61;
	IBOutlet FullColorWell *paletteColor62;
	IBOutlet FullColorWell *paletteColor63;
	IBOutlet FullColorWell *paletteColor64;
	IBOutlet FullColorWell *paletteColor65;
	IBOutlet FullColorWell *paletteColor66;
	IBOutlet FullColorWell *paletteColor67;
	IBOutlet FullColorWell *paletteColor68;
	IBOutlet FullColorWell *paletteColor69;
	IBOutlet FullColorWell *paletteColor70;
	IBOutlet FullColorWell *paletteColor71;
	IBOutlet FullColorWell *paletteColor72;
	IBOutlet FullColorWell *paletteColor73;
	IBOutlet FullColorWell *paletteColor74;
	IBOutlet FullColorWell *paletteColor75;
	IBOutlet FullColorWell *paletteColor76;
	IBOutlet FullColorWell *paletteColor77;
	IBOutlet FullColorWell *paletteColor78;
	IBOutlet FullColorWell *paletteColor79;
	IBOutlet FullColorWell *paletteColor80;
	IBOutlet FullColorWell *paletteColor81;
	IBOutlet FullColorWell *paletteColor82;
	IBOutlet FullColorWell *paletteColor83;
	IBOutlet FullColorWell *paletteColor84;
	IBOutlet FullColorWell *paletteColor85;
	IBOutlet FullColorWell *paletteColor86;
	IBOutlet FullColorWell *paletteColor87;
	IBOutlet FullColorWell *paletteColor88;
	IBOutlet FullColorWell *paletteColor89;
	IBOutlet FullColorWell *paletteColor90;
	IBOutlet FullColorWell *paletteColor91;
	IBOutlet FullColorWell *paletteColor92;
	IBOutlet FullColorWell *paletteColor93;
	IBOutlet FullColorWell *paletteColor94;
	IBOutlet FullColorWell *paletteColor95;
	IBOutlet FullColorWell *paletteColor96;
	IBOutlet FullColorWell *paletteColor97;
	IBOutlet FullColorWell *paletteColor98;
	IBOutlet FullColorWell *paletteColor99;
	IBOutlet FullColorWell *paletteColor100;
	IBOutlet FullColorWell *paletteColor101;
	IBOutlet FullColorWell *paletteColor102;
	IBOutlet FullColorWell *paletteColor103;
	IBOutlet FullColorWell *paletteColor104;
	IBOutlet FullColorWell *paletteColor105;
	IBOutlet FullColorWell *paletteColor106;
	IBOutlet FullColorWell *paletteColor107;
	IBOutlet FullColorWell *paletteColor108;
	IBOutlet FullColorWell *paletteColor109;
	IBOutlet FullColorWell *paletteColor110;
	IBOutlet FullColorWell *paletteColor111;
	IBOutlet FullColorWell *paletteColor112;
	IBOutlet FullColorWell *paletteColor113;
	IBOutlet FullColorWell *paletteColor114;
	IBOutlet FullColorWell *paletteColor115;
	IBOutlet FullColorWell *paletteColor116;
	IBOutlet FullColorWell *paletteColor117;
	IBOutlet FullColorWell *paletteColor118;
	IBOutlet FullColorWell *paletteColor119;
	IBOutlet FullColorWell *paletteColor120;
	IBOutlet FullColorWell *paletteColor121;
	IBOutlet FullColorWell *paletteColor122;
	IBOutlet FullColorWell *paletteColor123;
	IBOutlet FullColorWell *paletteColor124;
	IBOutlet FullColorWell *paletteColor125;
	IBOutlet FullColorWell *paletteColor126;
	IBOutlet FullColorWell *paletteColor127;
	IBOutlet FullColorWell *paletteColor128;
	IBOutlet FullColorWell *paletteColor129;
	IBOutlet FullColorWell *paletteColor130;
	IBOutlet FullColorWell *paletteColor131;
	IBOutlet FullColorWell *paletteColor132;
	IBOutlet FullColorWell *paletteColor133;
	IBOutlet FullColorWell *paletteColor134;
	IBOutlet FullColorWell *paletteColor135;
	IBOutlet FullColorWell *paletteColor136;
	IBOutlet FullColorWell *paletteColor137;
	IBOutlet FullColorWell *paletteColor138;
	IBOutlet FullColorWell *paletteColor139;
	IBOutlet FullColorWell *paletteColor140;
	IBOutlet FullColorWell *paletteColor141;
	IBOutlet FullColorWell *paletteColor142;
	IBOutlet FullColorWell *paletteColor143;
	IBOutlet FullColorWell *paletteColor144;
	IBOutlet FullColorWell *paletteColor145;
	IBOutlet FullColorWell *paletteColor146;
	IBOutlet FullColorWell *paletteColor147;
	IBOutlet FullColorWell *paletteColor148;
	IBOutlet FullColorWell *paletteColor149;
	IBOutlet FullColorWell *paletteColor150;
	IBOutlet FullColorWell *paletteColor151;
	IBOutlet FullColorWell *paletteColor152;
	IBOutlet FullColorWell *paletteColor153;
	IBOutlet FullColorWell *paletteColor154;
	IBOutlet FullColorWell *paletteColor155;
	IBOutlet FullColorWell *paletteColor156;
	IBOutlet FullColorWell *paletteColor157;
	IBOutlet FullColorWell *paletteColor158;
	IBOutlet FullColorWell *paletteColor159;
	IBOutlet FullColorWell *paletteColor160;
	IBOutlet FullColorWell *paletteColor161;
	IBOutlet FullColorWell *paletteColor162;
	IBOutlet FullColorWell *paletteColor163;
	IBOutlet FullColorWell *paletteColor164;
	IBOutlet FullColorWell *paletteColor165;
	IBOutlet FullColorWell *paletteColor166;
	IBOutlet FullColorWell *paletteColor167;
	IBOutlet FullColorWell *paletteColor168;
	IBOutlet FullColorWell *paletteColor169;
	IBOutlet FullColorWell *paletteColor170;
	IBOutlet FullColorWell *paletteColor171;
	IBOutlet FullColorWell *paletteColor172;
	IBOutlet FullColorWell *paletteColor173;
	IBOutlet FullColorWell *paletteColor174;
	IBOutlet FullColorWell *paletteColor175;
	IBOutlet FullColorWell *paletteColor176;
	IBOutlet FullColorWell *paletteColor177;
	IBOutlet FullColorWell *paletteColor178;
	IBOutlet FullColorWell *paletteColor179;
	IBOutlet FullColorWell *paletteColor180;
	IBOutlet FullColorWell *paletteColor181;
	IBOutlet FullColorWell *paletteColor182;
	IBOutlet FullColorWell *paletteColor183;
	IBOutlet FullColorWell *paletteColor184;
	IBOutlet FullColorWell *paletteColor185;
	IBOutlet FullColorWell *paletteColor186;
	IBOutlet FullColorWell *paletteColor187;
	IBOutlet FullColorWell *paletteColor188;
	IBOutlet FullColorWell *paletteColor189;
	IBOutlet FullColorWell *paletteColor190;
	IBOutlet FullColorWell *paletteColor191;
	IBOutlet FullColorWell *paletteColor192;
	IBOutlet FullColorWell *paletteColor193;
	IBOutlet FullColorWell *paletteColor194;
	IBOutlet FullColorWell *paletteColor195;
	IBOutlet FullColorWell *paletteColor196;
	IBOutlet FullColorWell *paletteColor197;
	IBOutlet FullColorWell *paletteColor198;
	IBOutlet FullColorWell *paletteColor199;
	IBOutlet FullColorWell *paletteColor200;
	IBOutlet FullColorWell *paletteColor201;
	IBOutlet FullColorWell *paletteColor202;
	IBOutlet FullColorWell *paletteColor203;
	IBOutlet FullColorWell *paletteColor204;
	IBOutlet FullColorWell *paletteColor205;
	IBOutlet FullColorWell *paletteColor206;
	IBOutlet FullColorWell *paletteColor207;
	IBOutlet FullColorWell *paletteColor208;
	IBOutlet FullColorWell *paletteColor209;
	IBOutlet FullColorWell *paletteColor210;
	IBOutlet FullColorWell *paletteColor211;
	IBOutlet FullColorWell *paletteColor212;
	IBOutlet FullColorWell *paletteColor213;
	IBOutlet FullColorWell *paletteColor214;
	IBOutlet FullColorWell *paletteColor215;
	IBOutlet FullColorWell *paletteColor216;
	IBOutlet FullColorWell *paletteColor217;
	IBOutlet FullColorWell *paletteColor218;
	IBOutlet FullColorWell *paletteColor219;
	IBOutlet FullColorWell *paletteColor220;
	IBOutlet FullColorWell *paletteColor221;
	IBOutlet FullColorWell *paletteColor222;
	IBOutlet FullColorWell *paletteColor223;
	IBOutlet FullColorWell *paletteColor224;
	IBOutlet FullColorWell *paletteColor225;
	IBOutlet FullColorWell *paletteColor226;
	IBOutlet FullColorWell *paletteColor227;
	IBOutlet FullColorWell *paletteColor228;
	IBOutlet FullColorWell *paletteColor229;
	IBOutlet FullColorWell *paletteColor230;
	IBOutlet FullColorWell *paletteColor231;
	IBOutlet FullColorWell *paletteColor232;
	IBOutlet FullColorWell *paletteColor233;
	IBOutlet FullColorWell *paletteColor234;
	IBOutlet FullColorWell *paletteColor235;
	IBOutlet FullColorWell *paletteColor236;
	IBOutlet FullColorWell *paletteColor237;
	IBOutlet FullColorWell *paletteColor238;
	IBOutlet FullColorWell *paletteColor239;
	IBOutlet FullColorWell *paletteColor240;
	IBOutlet FullColorWell *paletteColor241;
	IBOutlet FullColorWell *paletteColor242;
	IBOutlet FullColorWell *paletteColor243;
	IBOutlet FullColorWell *paletteColor244;
	IBOutlet FullColorWell *paletteColor245;
	IBOutlet FullColorWell *paletteColor246;
	IBOutlet FullColorWell *paletteColor247;
	IBOutlet FullColorWell *paletteColor248;
	IBOutlet FullColorWell *paletteColor249;
	IBOutlet FullColorWell *paletteColor250;
	IBOutlet FullColorWell *paletteColor251;
	IBOutlet FullColorWell *paletteColor252;
	IBOutlet FullColorWell *paletteColor253;
	IBOutlet FullColorWell *paletteColor254;
	IBOutlet FullColorWell *paletteColor255;
	IBOutlet FullColorWell *paletteColor256;
	
	NSNumber *offset;
	NSString *filename;
	NSString *layout;
	NSString *mode;
	NSMutableArray *palette;

	RomFileReader *imageReader;	
}

@property (readonly,copy) NSNumber* offset;
@property (readonly,copy) NSString* filename;
@property (readonly,copy) NSString* layout;
@property (readonly,copy) NSString* mode;
@property (readonly,copy) NSMutableArray* palette;

- (IBAction) copy:(id)sender;
- (IBAction) paste:(id)sender;
- (IBAction) openDirectory:(id)sender;
- (IBAction) incrementOffsetByOne:(id)sender;
- (IBAction) decrementOffsetByOne:(id)sender;
- (IBAction) incrementOffsetByPage:(id)sender;
- (IBAction) decrementOffsetByPage:(id)sender;
- (IBAction) offsetEntered:(id)sender;
- (IBAction) modeChanged:(id)sender;
- (IBAction) colorChanged:(id)sender;
- (IBAction) saveImage:(id)sender;
- (IBAction) importPalette:(id)sender;
- (IBAction) encodeFile:(id)sender;

- (void) awakeFromNib;
- (void) generateImage;
- (void) parsePalette:(NSString *)paletteFile;

@property (retain) NSMenu *menu;
@property (retain) NSWindow *window;
@property (retain) PixelImageView *mainImageView;
@property (retain) NSTextField *offsetField;
@property (retain) NSPopUpButton *modeComboBox;
@property (retain) NSPopUpButton *layoutComboBox;
@property (retain) NSButton *addOneByte;
@property (retain) NSButton *addOnePage;
@property (retain) NSButton *removeOneByte;
@property (retain) NSButton *removeOnePage;

@end
